### PR TITLE
Homework on Html basics#2 

### PR DESCRIPTION
**Pull request by dragan-andrei**
# Homework num 2

#### I've done my homework, based on lesson 7 and I've done additional work to improve my skills.
I used *required*, *checked*,*autocomplete* to make my website more comfortable for the typical user. I added these things to send sorted and only important info to the server, to protect server from incompetent info: *like email without "@"* or  **Чиназэс** in postal code block and more over😸

 I've passed through the validation site:
image
## What did I study: 
- Forms (Input types, Textarea's, name, method post/ get, id's, action).
- Buttons and their types.
- Fieldsets and legends.

## In the end I pint the photo of my website:
Снимок экрана 2024-03-14 145830

### We can't  ignore committed files to git. If we don't want to add some files to git:
- Adding only required files: git add *required file*
- We need delete this file from this branch and make git add.
## I am not an **Expert** in that deal, but this is how I feel it.

### CODE REVIEW

**Review by CozlovschiNichita — APPROVED** [review]
Умничка!

**Review by IvanCeban — CHANGES_REQUESTED** [review]
Good job!
I don't think you need to remove your previous homepage.
Better put it into a separate folder if you want to divide the homework somehow. 
Anyway your main branch should keep all your homeworks

**Comment by dragan-andrei** [comment]
### I know that I need all hw in *main*. I just have these files in *main branch* and I thought that I can delete them. At least, I have added them, I know *ALLES GUT*

**Comment by dragan-andrei** [comment]
image

## I have these files right now in my branch with the las HW.

**Pull request merged**
